version: "3.8"

services:
  resolver:
    build: .
    ports:
      - "5051:5051"
    environment:
      TMDB_KEY: "${TMDB_KEY:-}"
      PROXY_BASE_URL: "${PROXY_BASE_URL:-}"
      CATALOG_PATH: "/app/data/catalog.json"
    volumes:
      - ./data:/app/data
